"""empty message

Revision ID: 0197fe7d84d1
Revises: 3e4dc3d3c50f
Create Date: 2023-04-03 10:17:59.892024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0197fe7d84d1'
down_revision = '3e4dc3d3c50f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fertiberia')
    op.drop_table('bunge')
    op.add_column('soilfarmlands', sa.Column('name', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'soilfarmlands', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'soilfarmlands', type_='unique')
    op.drop_column('soilfarmlands', 'name')
    op.create_table('bunge',
    sa.Column('fertiberia_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fertilizer_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('crop_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nitrogen', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('phosphorus', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('potassium', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('calcium', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('sulfur', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('magnesium', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('magnesium_oxide', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('silicon_dioxide', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('zinc', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('copper', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('manganese', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('boron', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('molybdenum', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('fertiberia_id', name='bunge_pkey')
    )
    op.create_table('fertiberia',
    sa.Column('fertiberia_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fertilizer_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nitrogen_total_perc', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('nitrogen_ammoniacal_perc', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('nitrogen_ureic_perc', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('nitrogen_nitric_perc', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('phosphorus_2o5_total_perc', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('phosphorus_2o5_soluble_water_perc', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('phosphorus_2o5_soluble_water_neutral_ammonium_citrate_perc', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('phosphorus_2o5_soluble_neutral_ammonium_citrate_perc', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('potassium_2o2_soluble_water_perc', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('magnesium_oxide_total_perc', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('magnesium_oxide_soluble_water_perc', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('calcium_oxide_soluble_water_perc', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('sulfur_trioxide_total_perc', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('sulfur_trioxide_soluble_water_perc', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('boron_perc', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('boron_soluble_water_perc', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('ferrum_perc', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('ferrum_soluble_water_perc', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('zinc_total_perc', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('dcd_perc', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('sdcd_perc', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('solubility', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ph_aqueous_solution', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('fertiberia_id', name='fertiberia_pkey')
    )
    # ### end Alembic commands ###
